In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/water_pollution.csv")

df.shape
df.info()
df.head(10)
df.isna().sum()          # check missing values
df.duplicated().sum()    # check duplicates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3015 entries, 0 to 3014
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             2999 non-null   object
 1   City              2974 non-null   object
 2   Water Source      2984 non-null   object
 3   Pollutant Type    2979 non-null   object
 4   Pollution Level   2983 non-null   object
 5   pH                2959 non-null   float64
 6   Dissolved Oxygen  2965 non-null   float64
 7   Temperature       2987 non-null   float64
 8   Year              2993 non-null   float64
 9   Safe Limit        2989 non-null   object
dtypes: float64(4), object(6)
memory usage: 235.7+ KB

np.int64(15)

In [3]:
df = df.drop_duplicates()
df.shape

(3000, 10)

In [4]:
text_cols = ["State", "City", "Water Source", "Pollutant Type", "Pollution Level", "Safe Limit"]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()          # remove stray spaces
    df[col] = df[col].str.title()                       # consistent casing

df["Safe Limit"] = df["Safe Limit"].str.capitalize()     # Yes/No

In [5]:
df["Year"] = df["Year"].astype(str).str.replace(".0", "", regex=False)
df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")

In [6]:
# Numeric columns: fill with column median
num_cols = ["pH", "Dissolved Oxygen", "Temperature"]
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Categorical columns: fill with mode or "Unknown"
for col in text_cols + ["Year"]:
    df[col] = df[col].fillna(df[col].mode()[0])

In [7]:
df["pH"] = df["pH"].round(2)
df["Dissolved Oxygen"] = df["Dissolved Oxygen"].round(2)
df["Temperature"] = df["Temperature"].round(1)
df["Year"] = df["Year"].astype(int)

In [8]:
print(df['City'].unique())

['Vadodara' 'Ludhiana' 'Bengaluru' 'Dwarka' 'Silchar' 'Faridabad'
 'Dibrugarh' 'Sambalpur' 'Noida' 'Bhopal' 'Rajkot' 'Kota' 'Indore'
 'Kanpur' 'Jodhpur' 'Gaya' 'New Delhi' 'Bhavnagar' 'Darbhanga' 'Bikaner'
 'Nashik' 'Madurai' 'Lucknow' 'Guwahati' 'Patiala' 'Trichy' 'Nagaon'
 'Mysuru' 'Salem' 'Kozhikode' 'Saket' 'Ambala' 'Karnal' 'Pune' 'Jaipur'
 'Kochi' 'Panipat' 'Udaipur' 'Asansol' 'Ahmedabad' 'Varanasi' 'Berhampur'
 'Coimbatore' 'Siliguri' 'Rourkela' 'Kolkata' 'Ujjain' 'Nagpur' 'Patna'
 'Hubli' 'Rohini' 'Chennai' 'Nan' 'Jorhat' 'Karol Bagh' 'Cuttack'
 'Belgaum' 'Aurangabad' 'Amritsar' 'Mumbai' 'Agra' 'Muzaffarpur' 'Howrah'
 'Chandigarh' 'Kollam' 'Thrissur' 'Bhagalpur' 'Mangalore' 'Bhubaneswar'
 'Gwalior' 'Jabalpur' 'Jalandhar' 'Thiruvananthapuram' 'Gurugram' 'Surat'
 'Durgapur']

In [9]:
df.isnull().sum()

State               0
City                0
Water Source        0
Pollutant Type      0
Pollution Level     0
pH                  0
Dissolved Oxygen    0
Temperature         0
Year                0
Safe Limit          0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

                pH  Dissolved Oxygen  Temperature         Year
count  3000.000000       3000.000000  3000.000000  3000.000000
mean      6.991783          5.454440    24.169533  2019.558667
std       0.892022          1.802084     4.975102     2.882128
min       4.500000          0.500000     8.000000  2015.000000
25%       6.400000          4.260000    20.800000  2017.000000
50%       6.990000          5.430000    24.200000  2020.000000
75%       7.580000          6.680000    27.400000  2022.000000
max       9.800000         11.000000    38.000000  2024.000000

In [12]:
df.to_csv("water_pollution_cleaned.csv", index=False)